// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var TextInput = require("mineral-ui/TextInput");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -702382193,
    "jumbo"
  ],
  /* tuple */[
    -272944197,
    "large"
  ],
  /* tuple */[
    -20425611,
    "medium"
  ],
  /* tuple */[
    -9768761,
    "small"
  ]
];

function sizeToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray);
}

function sizeFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

var mapSizeToJs = sizeToJs;

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    164354652,
    "warning"
  ],
  /* tuple */[
    512905955,
    "danger"
  ],
  /* tuple */[
    944645571,
    "success"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray$1);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray$1, param);
}

var mapVariantToJs = variantToJs;

var jsMapperConstantArray$2 = /* array */[
  /* tuple */[
    -1033677266,
    "date"
  ],
  /* tuple */[
    -925883621,
    "password"
  ],
  /* tuple */[
    -856044371,
    "text"
  ],
  /* tuple */[
    -855847923,
    "time"
  ],
  /* tuple */[
    -822779916,
    "week"
  ],
  /* tuple */[
    -487088280,
    "search"
  ],
  /* tuple */[
    -271659236,
    "email"
  ],
  /* tuple */[
    5791195,
    "tel"
  ],
  /* tuple */[
    5843823,
    "url"
  ],
  /* tuple */[
    207603520,
    "month"
  ],
  /* tuple */[
    561678025,
    "number"
  ],
  /* tuple */[
    983036432,
    "datetime-local"
  ]
];

function inputTypeToJs(param) {
  return Js_mapperRt.binarySearch(12, param, jsMapperConstantArray$2);
}

function inputTypeFromJs(param) {
  return Js_mapperRt.revSearch(12, jsMapperConstantArray$2, param);
}

var mapInputTypeToJs = inputTypeToJs;

function make(defaultValue, disabled, iconEnd, iconStart, inputRef, invalid, onChange, prefix, readOnly, required, rootProps, size, suffix, _type, value, variant, children) {
  var tmp = { };
  if (defaultValue) {
    tmp.defaultValue = Js_primitive.valFromOption(defaultValue);
  }
  if (disabled) {
    tmp.disabled = Js_primitive.valFromOption(disabled);
  }
  if (iconEnd) {
    tmp.iconEnd = Js_primitive.valFromOption(iconEnd);
  }
  if (iconStart) {
    tmp.iconStart = Js_primitive.valFromOption(iconStart);
  }
  if (inputRef) {
    tmp.inputRef = Js_primitive.valFromOption(inputRef);
  }
  if (invalid) {
    tmp.invalid = Js_primitive.valFromOption(invalid);
  }
  if (onChange) {
    tmp.onChange = Js_primitive.valFromOption(onChange);
  }
  if (prefix) {
    tmp.prefix = Js_primitive.valFromOption(prefix);
  }
  if (readOnly) {
    tmp.readOnly = Js_primitive.valFromOption(readOnly);
  }
  if (required) {
    tmp.required = Js_primitive.valFromOption(required);
  }
  if (rootProps) {
    tmp.rootProps = Js_primitive.valFromOption(rootProps);
  }
  var tmp$1 = Js_option.map(mapSizeToJs, size);
  if (tmp$1) {
    tmp.size = Js_primitive.valFromOption(tmp$1);
  }
  if (suffix) {
    tmp.suffix = Js_primitive.valFromOption(suffix);
  }
  var tmp$2 = Js_option.map(mapInputTypeToJs, _type);
  if (tmp$2) {
    tmp.type = Js_primitive.valFromOption(tmp$2);
  }
  if (value) {
    tmp.value = Js_primitive.valFromOption(value);
  }
  var tmp$3 = Js_option.map(mapVariantToJs, variant);
  if (tmp$3) {
    tmp.variant = Js_primitive.valFromOption(tmp$3);
  }
  return ReasonReact.wrapJsForReason(TextInput.default, tmp, children);
}

var cmp = TextInput.default;

exports.sizeToJs = sizeToJs;
exports.sizeFromJs = sizeFromJs;
exports.mapSizeToJs = mapSizeToJs;
exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.mapVariantToJs = mapVariantToJs;
exports.inputTypeToJs = inputTypeToJs;
exports.inputTypeFromJs = inputTypeFromJs;
exports.mapInputTypeToJs = mapInputTypeToJs;
exports.make = make;
exports.cmp = cmp;
/* cmp Not a pure module */
