// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Themes = require("mineral-ui/themes");

function make(theme, children) {
  var tmp = { };
  if (theme) {
    tmp.theme = Js_primitive.valFromOption(theme);
  }
  return ReasonReact.wrapJsForReason(Themes.ThemeProvider, tmp, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
