// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Button = require("mineral-ui/Button");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -702382193,
    "jumbo"
  ],
  /* tuple */[
    -272944197,
    "large"
  ],
  /* tuple */[
    -20425611,
    "medium"
  ],
  /* tuple */[
    -9768761,
    "small"
  ]
];

function sizeToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray);
}

function sizeFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

var mapSizeToJs = sizeToJs;

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    164354652,
    "warning"
  ],
  /* tuple */[
    512905955,
    "danger"
  ],
  /* tuple */[
    944645571,
    "success"
  ]
];

function variantToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray$1);
}

function variantFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray$1, param);
}

var mapVariantToJs = variantToJs;

function make(circular, disabled, element, fullWidth, iconEnd, iconStart, minimal, onClick, primary, size, _type, variant, children) {
  var tmp = { };
  if (circular) {
    tmp.circular = Js_primitive.valFromOption(circular);
  }
  if (disabled) {
    tmp.disabled = Js_primitive.valFromOption(disabled);
  }
  if (element) {
    tmp.element = Js_primitive.valFromOption(element);
  }
  if (fullWidth) {
    tmp.fullWidth = Js_primitive.valFromOption(fullWidth);
  }
  if (iconEnd) {
    tmp.iconEnd = Js_primitive.valFromOption(iconEnd);
  }
  if (iconStart) {
    tmp.iconStart = Js_primitive.valFromOption(iconStart);
  }
  if (minimal) {
    tmp.minimal = Js_primitive.valFromOption(minimal);
  }
  if (onClick) {
    tmp.onClick = Js_primitive.valFromOption(onClick);
  }
  if (primary) {
    tmp.primary = Js_primitive.valFromOption(primary);
  }
  var tmp$1 = Js_option.map(mapSizeToJs, size);
  if (tmp$1) {
    tmp.size = Js_primitive.valFromOption(tmp$1);
  }
  if (_type) {
    tmp.type = Js_primitive.valFromOption(_type);
  }
  var tmp$2 = Js_option.map(mapVariantToJs, variant);
  if (tmp$2) {
    tmp.variant = Js_primitive.valFromOption(tmp$2);
  }
  return ReasonReact.wrapJsForReason(Button.default, tmp, children);
}

exports.sizeToJs = sizeToJs;
exports.sizeFromJs = sizeFromJs;
exports.mapSizeToJs = mapSizeToJs;
exports.variantToJs = variantToJs;
exports.variantFromJs = variantFromJs;
exports.mapVariantToJs = mapVariantToJs;
exports.make = make;
/* ReasonReact Not a pure module */
